name = "DecisionRules"
uuid = "47937410-f832-486f-8300-12c95b225dfc"
authors = ["Andrew <arosemberg3@gatech.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
ChainRules = "082447d4-558c-5d27-93f4-14fc19e9eca2"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DiffOpt = "930fe3bc-9c6b-11ea-2d94-6184641e85e7"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
ParametricOptInterface = "0ce4ce61-57bf-432b-a095-efac525d185e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ChainRules = "1.72.6"
ChainRulesCore = "1.25.2"
DiffOpt = "0.5.4"
FillArrays = "1.14.0"
Flux = "0.14.21"
JLD2 = "0.6.3"
JuMP = "1.29.4"
MathOptInterface = "1.48.0"
ParametricOptInterface = "0.14.1"
Zygote = "0.6.77, 0.7"
julia = "~1.9, 1.10"

[extras]
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "Zygote", "Ipopt"]
