[deps]
DecisionRules = "47937410-f832-486f-8300-12c95b225dfc"
DiffOpt = "930fe3bc-9c6b-11ea-2d94-6184641e85e7"
Dojo = "ac60b53e-8d92-4c83-b960-e78698fa1916"
DojoEnvironments = "8728bab7-e8ae-46fd-a1b6-a8c4d00f608e"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HSL_jll = "017b0a0e-03f4-516a-9b91-836bbd1904dd"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
