[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Dojo = "ac60b53e-8d92-4c83-b960-e78698fa1916"
DojoEnvironments = "8728bab7-e8ae-46fd-a1b6-a8c4d00f608e"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
