[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ClosedIntervals = "059b0e18-018a-5deb-a5b2-c624ee85784b"
Crux = "e51cc422-768a-4345-bb8e-2246287ae729"
Dojo = "ac60b53e-8d92-4c83-b960-e78698fa1916"
DojoEnvironments = "8728bab7-e8ae-46fd-a1b6-a8c4d00f608e"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
